platform :ios, '10.0'
use_frameworks!

target 'TactileButton_Example' do
  pod 'TactileButton', :path => '../'

  target 'TactileButton_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['(FRAMEWORK_SEARCH_PATHS)']
    end
end
